spring.application.name=task-manager
server.port=8080

# Активный профиль для разработки
spring.profiles.active=dev

# Настройки логирования
logging.level.com.example.task_manager=DEBUG
logging.level.org.springframework=INFO
